CREATE TABLE "video" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "hash" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "day" INTEGER NOT NULL,
  "month" INTEGER NOT NULL,
  "createdAt" DATETIME DEFAULT CURRENT_TIMESTAMP, 
  "updatedAt" DATETIME
);